name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/Parcial_BigData_front
          ENVIRONMENT: Parcial_front
      
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del proyecto
              cd Parcial_BigData_front/ && ls &&

              # Activar el entorno virtual
              source env/bin/activate &&

              # Actualizar el código desde la rama main
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&

              # Instalar dependencias necesarias
              pip install -r requirements.txt &&

              # Navegar al directorio react_front
              cd ../react_front/ &&

              # Instalar dependencias de npm
              sudo npm install &&

              # Iniciar la aplicación de React
              sudo npm start
          '
